package desktopapplication1;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lakshit
 */
public class Accountinfo extends javax.swing.JFrame {

    /**
     * Creates new form Accountinfo
     */
    public Accountinfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        orders_btn = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        adress_change_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        feedback_btn = new javax.swing.JButton();
        logout_btn = new javax.swing.JButton();
        back_btn = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("ACCOUNT INFORMATION");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        orders_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button (4).jpg"))); // NOI18N
        orders_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orders_btnActionPerformed(evt);
            }
        });
        getContentPane().add(orders_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 150, 40));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button (3).jpg"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 210, 40));

        adress_change_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button (1).jpg"))); // NOI18N
        adress_change_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adress_change_btnActionPerformed(evt);
            }
        });
        getContentPane().add(adress_change_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 290, 40));

        jLabel1.setFont(new java.awt.Font("Samarkan", 1, 48));
        jLabel1.setForeground(new java.awt.Color(52, 142, 52));
        jLabel1.setText("ACCOUNT INFO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 410, 50));

        feedback_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button.jpg"))); // NOI18N
        feedback_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feedback_btnActionPerformed(evt);
            }
        });
        getContentPane().add(feedback_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 210, 40));

        logout_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button (2).jpg"))); // NOI18N
        logout_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_btnActionPerformed(evt);
            }
        });
        getContentPane().add(logout_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, 90, 30));

        back_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button.png"))); // NOI18N
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        getContentPane().add(back_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, 90, 30));

        jButton15.setBackground(new java.awt.Color(255, 255, 255));
        jButton15.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jButton15.setForeground(new java.awt.Color(153, 0, 0));
        jButton15.setText("X");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Abstract-Backgorund-with-Butterfly-Vector (Copy).jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 0, 700, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void orders_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orders_btnActionPerformed
new order_history().setVisible(true);      // TODO add your handling code here:
}//GEN-LAST:event_orders_btnActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
new change_pwd().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void adress_change_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adress_change_btnActionPerformed
new change_address().setVisible(true);        // TODO add your handling code here:
}//GEN-LAST:event_adress_change_btnActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
       // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void feedback_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feedback_btnActionPerformed
new enter_feedback().setVisible(true);        // TODO add your handling code here:
}//GEN-LAST:event_feedback_btnActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        this.setVisible(false);
        new exit().setVisible(true);       // TODO add your handling code here:
}//GEN-LAST:event_jButton15ActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
this.dispose();
new buttoncategories().setVisible(true);// TODO add your handling code here:
}//GEN-LAST:event_back_btnActionPerformed

    private void logout_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_btnActionPerformed
this.dispose();
var.cart[0].removeAll();
var.cart[1].removeAll();
new start_page().setVisible(true);// TODO add your handling code here:
}//GEN-LAST:event_logout_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Accountinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Accountinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Accountinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Accountinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Accountinfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adress_change_btn;
    private javax.swing.JButton back_btn;
    private javax.swing.JButton feedback_btn;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton logout_btn;
    private javax.swing.JButton orders_btn;
    // End of variables declaration//GEN-END:variables
}
