/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * admin_login.java
 *
 * Created on Jan 24, 2016, 3:33:51 PM
 */

package desktopapplication1;

import javax.swing.JOptionPane;
import java.sql.*;
/**
 *
 * @author Administrator
 */
public class admin_login extends javax.swing.JFrame {

    /** Creates new form admin_login */
    public admin_login() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pwd = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        uname = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("ADMINISTRATIVE LOGIN");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pwd.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.lightGray));
        pwd.setName("pwd"); // NOI18N
        pwd.setOpaque(false);
        getContentPane().add(pwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 240, 20));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 90, 90));

        uname.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.lightGray));
        uname.setName("uname"); // NOI18N
        uname.setOpaque(false);
        getContentPane().add(uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 240, 20));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button(1).png"))); // NOI18N
        jButton3.setName("jButton3"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 50, 50));

        jButton15.setBackground(new java.awt.Color(255, 255, 255));
        jButton15.setFont(new java.awt.Font("Comic Sans MS", 1, 18));
        jButton15.setForeground(new java.awt.Color(153, 0, 0));
        jButton15.setText("X");
        jButton15.setName("jButton15"); // NOI18N
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 50, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(0, 153, 102));
        jLabel1.setText("USERNAME");
        jLabel1.setName("jLabel1"); // NOI18N
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 70, 20));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Copy of hjagajd.png"))); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String username=uname.getText();
        if (username.isEmpty()) {
            pwd.setText("");
            JOptionPane.showMessageDialog(null,"User name can not be empty");
        } else {
            try {
                Class.forName("java.sql.DriverManager");
                Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/ipproject","root", "123");
                Statement stmt = (Statement) con.createStatement();
                String query="SELECT password,username FROM admin_login WHERE username='"+username+"';";
                ResultSet rs=stmt.executeQuery(query);
                if (rs.next()) {
                    String password = new String(pwd.getPassword());
                    if(password.equals(rs.getString("password"))&&username.equals(rs.getString("username"))) {

                        new admin_home().setVisible(true);
                        this.dispose();


                    } else {

                        JOptionPane.showMessageDialog(null,"Wrong Username or Password");
                    }
                } else {
                    JOptionPane.showMessageDialog(null,"Wrong Username or Password");

                }
            }

            catch(Exception e) {
                JOptionPane.showMessageDialog(null,e.getMessage());
            }
        }            // TODO add your handling code here:
}//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
       // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
        new start_page().setVisible(true);// TODO add your handling code here:
}//GEN-LAST:event_jButton3ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        this.dispose();
        new exit().setVisible(true);       // TODO add your handling code here:
}//GEN-LAST:event_jButton15ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField pwd;
    private javax.swing.JTextField uname;
    // End of variables declaration//GEN-END:variables

}
