package desktopapplication1;


import java.awt.Dimension;
import java.sql.*;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Student
 */
public class search extends javax.swing.JFrame {

    /**
     * Creates new form search
     */
    public search() {
        initComponents();
        jButton2.doClick();
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("SEARCH RESULTS");
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(100, 100, 700, 500));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot (4).png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/482300283.jpg"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Century Schoolbook", 1, 18));
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot (3).png"))); // NOI18N
        jButton8.setText("0");
        jButton8.setIconTextGap(-50);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton15.setBackground(new java.awt.Color(255, 255, 255));
        jButton15.setFont(new java.awt.Font("Comic Sans MS", 1, 18));
        jButton15.setForeground(new java.awt.Color(153, 0, 0));
        jButton15.setText("X");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot (5).png"))); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 504, Short.MAX_VALUE)
                .addComponent(jButton15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jButton15))
                .addContainerGap(496, Short.MAX_VALUE))
        );

        jButton8.setText(""+var.cart[0].getItemCount());

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
 
 
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
private void show_about(java.awt.event.ActionEvent evt)
 {
    var.product_info_code= Integer.parseInt(((JButton)evt.getSource()).getActionCommand());
    new productinfo().setVisible(true);
 }
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
String srch_str=var.srch;
JPanel main_panel = new javax.swing.JPanel();

main_panel.setLayout(null);
try
    {
        Class.forName("java.sql.DriverManager");
        Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/ipproject","root", "123");
        Statement stmt = (Statement) con.createStatement();
        String query="SELECT * FROM PRODUCT WHERE NAME LIKE '%"+srch_str+"%' OR MANUFACTURER LIKE '%"+srch_str+"%' OR TAG LIKE '%"+srch_str+"%';";
        ResultSet rs=stmt.executeQuery(query);

        int number=0;
        while(rs.next())
        {

           number++;
        }
        if(number==0)
        {
            JOptionPane.showMessageDialog(this,"NO RESULT WAS FOUND. PLEASE TRY ANOTHER KEYWORD \nOR TRY BROWSING BY CATEGORIES.");
        }
        JPanel[] panels = new javax.swing.JPanel[number];
        JButton[] buttons = new javax.swing.JButton[number];
        JButton[] atc_buttons = new javax.swing.JButton[number];
        JLabel[] names=new JLabel[number];
        JLabel[] price_disp=new JLabel[number];
        int[] price=new int[number];
        rs.first();
        int i=0;
        while(i<number)
        {
            panels[i]=new JPanel();
            panels[i].setLayout(null);
            buttons[i]=new JButton();
            atc_buttons[i]=new JButton();
            atc_buttons[i].setText("ADD TO CART");
            names[i]=new JLabel();
            price_disp[i]=new JLabel();
            String image_address="/Document_files/product_original ("+rs.getInt("codeno")+").png";
            buttons[i].setIcon(new javax.swing.ImageIcon(getClass().getResource(image_address)));
            buttons[i].setActionCommand(""+rs.getInt("codeno"));
            atc_buttons[i].setActionCommand(""+rs.getInt("codeno"));
            names[i].setText(rs.getString("name").toUpperCase());
            price_disp[i].setText("$ "+rs.getInt("price"));
            price[i]=rs.getInt("price");
            buttons[i].setToolTipText(rs.getString("name"));
            names[i].setBounds(0,300,300,30);
            buttons[i].setBounds(0,0,300,300);
            price_disp[i].setBounds(0,340,300,30);
            atc_buttons[i].setBounds(0,380,300,30);
            panels[i].add(buttons[i]);
            panels[i].add(atc_buttons[i]);
            panels[i].add(names[i]);
            panels[i].add(price_disp[i]);
            main_panel.add(panels[i]);
            panels[i].setBounds((i%3)*350,460*(i/3),300,410);
            main_panel.revalidate();
            final int price_i=price[i];
            final String p_name=names[i].getText();
            atc_buttons[i].addActionListener(new java.awt.event.ActionListener() {public void actionPerformed(java.awt.event.ActionEvent evt) {act_evt(evt,price_i,p_name);}});
            buttons[i].addActionListener(new java.awt.event.ActionListener() {public void actionPerformed(java.awt.event.ActionEvent evt) {show_about(evt);}});
            i++;
            rs.next();




        }

            int height;
            if(i%3==0)
                height=460*i/3+100;
            else
                height=(i/3+1)*460+100;

            main_panel.setPreferredSize(new Dimension(1000,height));
            JScrollPane scroll_pane = new javax.swing.JScrollPane();
            scroll_pane.setBounds(10, 60, 1050, 500);
            scroll_pane.setViewportView(main_panel);
            this.add(scroll_pane);
            this.invalidate();
            this.validate();

        }
catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
           
        }

    }
private void act_evt(java.awt.event.ActionEvent evt,int price,String name)
 {

       int pcode= Integer.parseInt(((JButton)evt.getSource()).getActionCommand());
       int counter;
       boolean exists=false;
       for(counter=0;counter<var.cart[0].getItemCount();counter++)
       {
           if(Integer.parseInt(var.cart[0].getItem(counter))==pcode)
           {
               exists=true;
               break;

           }

       }
       if(exists)
       {
           var.cart[1].replaceItem(""+(Integer.parseInt(var.cart[1].getItem(counter))+1), counter);
           var.total+=price;
       }
       else
       {
           var.cart[0].add(""+pcode);
           var.cart[1].add(""+1);
           var.total+=price;
       }
       JOptionPane.showMessageDialog(this, name+" for $ "+price+" has been added to cart.");
       jButton8.setText(""+var.cart[0].getItemCount());// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
    this.dispose();
    new buttoncategories().setVisible(true);
    // TODO add your handling code here:
}//GEN-LAST:event_jButton7ActionPerformed

private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
    // TODO add your handling code here:
}//GEN-LAST:event_jTextField1KeyTyped

private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
    var.srch=jTextField1.getText();
    new search().setVisible(true);
    this.dispose();
}//GEN-LAST:event_jButton9ActionPerformed

private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
    new cart().setVisible(true);
    this.dispose();// TODO add your handling code here:
}//GEN-LAST:event_jButton8ActionPerformed

private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
    this.dispose();
    new exit().setVisible(true);       // TODO add your handling code here:
}//GEN-LAST:event_jButton15ActionPerformed

private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
    new Accountinfo().setVisible(true);
    this.dispose();        // TODO add your handling code here:
}//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new search().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
