package desktopapplication1;


import java.awt.AWTException;
import java.awt.Dimension;
import java.awt.Robot;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Student
 */
public class tt extends javax.swing.JFrame {

    /**
     * Creates new form tt
     */
    public tt() {
        initComponents();
        jButton1.doClick();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addComponent(jButton1)
                .addContainerGap(288, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jButton1)
                .addContainerGap(192, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

int i=0;
JPanel[] j = new javax.swing.JPanel[200];
JButton[] t = new javax.swing.JButton[200];
JLabel[] z=new JLabel[200];
JPanel jPanel2 = new javax.swing.JPanel();

jPanel2.setLayout(null);


while(i<200)
{
    j[i]=new JPanel();
    j[i].setLayout(null);
    t[i]=new JButton();
    z[i]=new JLabel();
    t[i].setText(""+i);
    z[i].setText("this"+i);
    z[i].setBounds(0,50,100,30);
    t[i].setBounds(0,0,100,30);
    j[i].add(t[i]);
    j[i].add(z[i]);
    jPanel2.add(j[i]);
    j[i].setBounds((i%3)*100,200*(i/3),100,200);
    jPanel2.revalidate();
   
    t[i].addActionListener(new java.awt.event.ActionListener() {public void actionPerformed(java.awt.event.ActionEvent g) {kl(g);}});
     
    i++;
    
}
jPanel2.setPreferredSize(new Dimension(250,5000));
JScrollPane l=new javax.swing.JScrollPane();
l.setBounds(0,0,350,500);
l.setViewportView(jPanel2);
this.add(l);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
public static int u;
    private void kl(java.awt.event.ActionEvent g)
    {
        System.out.print(((JButton)g.getSource()).getText());
        u=Integer.parseInt(((JButton)g.getSource()).getText());
        new test().setVisible(true);
        this.dispose();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
