/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * update_status.java
 *
 * Created on Jan 24, 2016, 4:10:24 PM
 */

package desktopapplication1;

import javax.swing.JOptionPane;
import java.sql.*;
/**
 *
 * @author Administrator
 */
public class update_status extends javax.swing.JFrame {

    /** Creates new form update_status */
    public update_status() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("UPDATE ORDER STATUS");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jRadioButton1.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("CANCEL");
        jRadioButton1.setName("jRadioButton1"); // NOI18N
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 52, -1, -1));

        jRadioButton2.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("PROCESSING");
        jRadioButton2.setName("jRadioButton2"); // NOI18N
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 78, -1, -1));

        jRadioButton3.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setText("IN TRANSIT");
        jRadioButton3.setName("jRadioButton3"); // NOI18N
        getContentPane().add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 104, -1, -1));

        jRadioButton4.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton4.setText("DELIVERED");
        jRadioButton4.setName("jRadioButton4"); // NOI18N
        getContentPane().add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 130, -1, -1));

        jButton1.setText("UPDATE STATUS");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 150, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setName("jLabel1"); // NOI18N
        jLabel1.setText("UPDATE ORDER STATUS FOR ORDER NO. "+var.update_order_no);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, 367, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg1.jpg"))); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-360, 0, 760, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
boolean do_execute=false;
String status = "";
if(jRadioButton1.isSelected())
{
    if(var.cancel_order(var.update_order_no))
    {
        JOptionPane.showMessageDialog(this,"ORDER STATUS UPDATED SUCCESSFULY");
    }
    else
    {
        JOptionPane.showMessageDialog(this,"ORDER STATUS UPDATE FAILED");
    }
}
 else if(jRadioButton2.isSelected())
{
             status="PROCESSING";
             do_execute=true;
}
 else if(jRadioButton3.isSelected())
{
             status="IN TRANSIT";
             do_execute=true;
}
 else if(jRadioButton4.isSelected())
{
             status="DELIVERED";
             do_execute=true;
}
 else
 {
    JOptionPane.showMessageDialog(this,"PLEASE SELECT ORDER STATUS TO UPDATE.");
 }
if(do_execute)
{
    try
    {
              Class.forName("java.sql.DriverManager");
              Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/ipproject", "root", "123");
              Statement stmt = (Statement) con.createStatement();
              String query="update orders set order_status='"+status+"' where order_no="+var.update_order_no+";";
              stmt.executeUpdate(query);
              JOptionPane.showMessageDialog(this,"ORDER STATUS UPDATED SUCCESSFULY");
              this.dispose();
    }
    catch(Exception e)
    {
              JOptionPane.showMessageDialog(null,e.getMessage());
              JOptionPane.showMessageDialog(this,"ORDER STATUS UPDATE FAILED");
    }
}this.dispose();

// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new update_status().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    // End of variables declaration//GEN-END:variables

}
