/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * view_feedback.java
 *
 * Created on Jan 24, 2016, 5:12:52 PM
 */

package desktopapplication1;
import java.awt.Dimension;
import java.sql.*;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
/**
 *
 * @author Administrator
 */
public class view_feedback extends javax.swing.JFrame {

    /** Creates new form view_feedback */
    public view_feedback() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        jButton1.setText("jButton1");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("FEEDBACK");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 217, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 457, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed


            // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
JPanel main_panel = new javax.swing.JPanel();

main_panel.setLayout(null);
try
    {
        Class.forName("java.sql.DriverManager");
        Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/ipproject","root", "123");
        Statement stmt = (Statement) con.createStatement();
        String query="SELECT * FROM feedback ;";
        ResultSet rs=stmt.executeQuery(query);

        int number=0;
        while(rs.next())
        {

           number++;
        }
        JTextArea[] txt_areas=new JTextArea[number];
        JPanel[] panels = new javax.swing.JPanel[number];
        JLabel[] user=new JLabel[number];
        rs.first();
        int i=0;
        while(i<number)
        {
            panels[i]=new JPanel();
            panels[i].setLayout(null);
            txt_areas[i]=new JTextArea();
            user[i]=new JLabel();
            txt_areas[i].setText(rs.getString(2));
            user[i].setText("BY-"+rs.getString(1));
            txt_areas[i].setBounds(0,0,164,94);
            user[i].setBounds(0,98,164,30);
            panels[i].add(txt_areas[i]);
            panels[i].add(user[i]);
            main_panel.add(panels[i]);
            panels[i].setBounds(0,130*i,170,120);
            i++;
            rs.next();
        }
            main_panel.setPreferredSize(new Dimension(180,i*130));
            JScrollPane scroll_pane = new javax.swing.JScrollPane();
            scroll_pane.setBounds(10, 60, 205,300 );
            scroll_pane.setViewportView(main_panel);
            this.add(scroll_pane);
        }
catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
this.invalidate();
this.validate();// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new view_feedback().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables

}
