/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * view_order.java
 *
 * Created on Jan 24, 2016, 12:51:29 PM
 */

package desktopapplication1;

import java.awt.Dimension;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class view_order extends javax.swing.JFrame {

    /** Creates new form view_order */
    public view_order() {
        initComponents();
        jButton1.doClick();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jButton1.setText("jButton1");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ORDER CONTENTS");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("PRODUCT");
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText("PRICE");
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText("QUANTITY");
        jLabel3.setName("jLabel3"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 233, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(71, 71, 71))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addContainerGap(502, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed


             // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
var.view_order[0].removeAll();
var.view_order[1].removeAll();// TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        JScrollPane scrl_pane = new javax.swing.JScrollPane();
   JPanel main_panel = new javax.swing.JPanel();
        int i = 0;



        try
        {
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/ipproject", "root", "123");
            Statement stmt = (Statement) con.createStatement();
            String query="select * from order"+var.view_order_code+";";
            ResultSet rs=stmt.executeQuery(query);
            while(rs.next())
            {
                var.view_order[0].add(rs.getString(1));
                var.view_order[1].add(rs.getString(2));
            }
            JPanel[] panel = new javax.swing.JPanel[var.view_order[0].getItemCount()];
            JLabel[] name_lbl = new JLabel[var.view_order[0].getItemCount()];
            JLabel[] img_lbl =new javax.swing.JLabel[var.view_order[0].getItemCount()];
            JLabel[] price_lbl = new JLabel[var.view_order[0].getItemCount()];
            JLabel[] qty_lbl = new JLabel[var.view_order[0].getItemCount()];

            main_panel.setLayout(null);
            while (i < var.view_order[0].getItemCount()) {
                query = "SELECT NAME,PRICE FROM PRODUCT WHERE CODENO=" + Integer.parseInt(var.view_order[0].getItem(i)) + ";";
                rs = stmt.executeQuery(query);
                rs.next();
                panel[i] = new JPanel();
                panel[i].setLayout(null);
                name_lbl[i] = new JLabel();
                price_lbl[i] = new JLabel();
                qty_lbl[i]=new JLabel();
                img_lbl[i]=new JLabel();
                name_lbl[i].setText(rs.getString("name").toUpperCase());
                price_lbl[i].setText("$ "+rs.getInt("price"));
                qty_lbl[i].setText(var.view_order[1].getItem(i));
                String image_address="/Document_files/product_original ("+var.view_order[0].getItem(i)+").png";
                img_lbl[i].setIcon(new javax.swing.ImageIcon(getClass().getResource(image_address)));
                img_lbl[i].setBounds(0,0,300,300);
                name_lbl[i].setBounds(0, 305, 300, 30);
                price_lbl[i].setBounds(320, 0, 50, 30);
                qty_lbl[i].setBounds(370,0,50,30);
                panel[i].add(name_lbl[i]);
                panel[i].add(price_lbl[i]);
                panel[i].add(qty_lbl[i]);
                panel[i].add(img_lbl[i]);
                main_panel.add(panel[i]);
                panel[i].setBounds(0, 340 * i, 410, 340);
                i++;

            }
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }


        main_panel.setPreferredSize(new Dimension(450, i*340+100));

        scrl_pane.setBounds(10, 90, 450, 500);
        scrl_pane.setViewportView(main_panel);
        this.add(scrl_pane);
        this.invalidate();
        this.validate();// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new view_order().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

}
